### ISSUE TITLE
About extract_patches.py

### ISSUE THREAD

**Issue by liuzhisheng1226** [arjunvekariyagithub/Camelyon16-grand-challenge#1]
In extract_patches.py:
  def find_roi_bbox_tumor_gt_mask(self,mask_image):
       bounding_boxes=self.get_bbox(np.array(mask))
But
   def get_bbox(cont_img,image),has two parameters....
Is it a bug???

**Comment by arjunvekariyagithub** [comment]
@liuzhisheng1226 Thanks for pointing out. Yes it was mistake. I added second parameters for get_bbox() as it was required while accessing from other modules. It is fixed now.

Happy to help!
