### ISSUE TITLE
How to get 'tif' mask

### ISSUE THREAD

**Issue by s10133679** [arjunvekariyagithub/Camelyon16-grand-challenge#10]
Hi, I noticed that the mask used in the work is different from the original dataset ('tif' instead of 'png'), can I know how did you generate the mask files as 'tif' format?

**Comment by s10133679** [comment]
I found the answer myself, by using ASAP, snippets are in https://camelyon17.grand-challenge.org/Data/

**Comment by li10141110** [comment]
@s10133679 hi,could you please show us the code for generating mask tif files by ASAP.I only got binary files. Following is my code:
import multiresolutionimageinterface as mir
reader = mir.MultiResolutionImageReader()
output_path = '/home/imdl/projects/camelyon17_type_mask_false'
mr_image = reader.open('/home/imdl/projects/Camelyon16/training/tumor/tumor_100.tif')
annotation_list = mir.AnnotationList()
xml_repository = mir.XmlRepository(annotation_list)
xml_repository.setSource('/home/imdl/projects/Camelyon16/training/lesion_annotations/tumor_100.xml')
xml_repository.load()
annotation_mask = mir.AnnotationToMask()
camelyon17_type_mask = False
label_map = {'metastases': 1, 'normal': 2} if camelyon17_type_mask else {'_0': 1, '_1': 1, '_2': 0}
conversion_order = ['metastases', 'normal'] if camelyon17_type_mask else  ['_0', '_1', '_2']
annotation_mask.convert(annotation_list, output_path, mr_image.getDimensions(), mr_image.getSpacing(), label_map, conversion_order)
need help~~

**Comment by s4384596** [comment]
Hi, your code is exactly the same as mine, I use this to generate binary masks for further image processing.

**Comment by s10133679** [comment]
Hi, your code is same as mine, I use this to generate binary mask for further processing.

**Comment by li10141110** [comment]
@s10133679 Thank you for your kind reply and may I have your wechat ID or Whatsapp or facebook for more help about Camelyon16? Thank you again!
