### ISSUE TITLE
wsi_ops

### ISSUE THREAD

**Issue by liuzhisheng1226** [arjunvekariyagithub/Camelyon16-grand-challenge#2]
def get_bbox(cont_img, rgb_image=None):
  | _, contours, _ = cv2.findContours(cont_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

cv2.findContours return 2 parameters,Not 3 parameters.

**Comment by arjunvekariyagithub** [comment]
@liuzhisheng1226 No, It returns 3 values. Please check [this official document](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_contours/py_contours_begin/py_contours_begin.html).
